### ISSUE TITLE
Issues with wthit?

### ISSUE THREAD

**Issue by VaporeonScripts** [Minecraft-LightLand/L2Weaponry#13]
[13Sep2024 18:20:29.167] [Render thread/ERROR] [mcp.mobius.waila.service.ApiService/]: [WTHIT] Unsolvable tier comparison!
Either one of [l2complements:requires_sculk_tool] or [minecraft:incorrect_for_wooden_tool] does not contain all entries from the other one.
The comparison is based on the assumption that lower tier's incorrect block tag contains all entries from higher tier's tag.
This was fine for Vanilla, but might be not match modded behavior.
Please open an issue at https://github.com/badasintended/wthit/issues

https://mclo.gs/VmzY6v5

**Comment by VaporeonScripts** [comment]
https://github.com/badasintended/wthit/issues/291#issuecomment-2349377431

**Comment by lcy0x1** [comment]
It seems to be a remainder of a feature that is no longer possible on 1.21

I will remove it and push a fix

**Comment by lcy0x1** [comment]
fixed
