### ISSUE TITLE
If I bring any item in this mod to the hotbar and hover the cursor over it, the game crashes immediately. Or if player equip that

### ISSUE THREAD

**Issue by X-Machiavelli** [Minecraft-LightLand/L2Weaponry#14]
[crash-2024-09-17_11.28.11-client.txt](https://github.com/user-attachments/files/17022196/crash-2024-09-17_11.28.11-client.txt)
[latest.log](https://github.com/user-attachments/files/17022197/latest.log)

environment: client or server both
launcher: neoforge21.1.54, MC1.21.1
mod: l2weaponry-3.0.1+3.jar, l2library-3.0.2+4.jar, l2complements-3.0.2+7.jar (I was mistaken. It seems to conflict with other mods, not the family package.)

I hope this issue can be improved.

**Comment by X-Machiavelli** [comment]
When combined with 'better combat', the crash is reproduced.

**Comment by lcy0x1** [comment]
Which version of this mod and better combat are you using?

**Comment by X-Machiavelli** [comment]
bettercombat-neoforge-2.0.3+1.21.1.jar + [l2weaponry-3.0.1+3.jar, l2library-3.0.2+4.jar, l2complements-3.0.2+7.jar]

**Comment by Dr-WeiAL** [comment]
fixed
