### ISSUE TITLE
neo 21.1.62 报错 MixinTransformerError

### ISSUE THREAD

**Issue by shenyx110** [Minecraft-LightLand/L2Weaponry#15]
1.21.1 neo21.1.62
[crash-2024-09-27_21.24.24-client.txt](https://github.com/user-attachments/files/17164801/crash-2024-09-27_21.24.24-client.txt)
（似乎更新neo forge到62后很多mod都出问题了 61就好好的）

**Comment by lcy0x1** [comment]
这个是FML阶段的报错，这个阶段任何一个mod出问题都会导致所有mod都报错，然后crash report就会随便选一个mod背锅。你给我看看latest.log

**Comment by shenyx110** [comment]
在今日的n个模组更新后奇迹般的全都好了
neoforge也更新全都没事了
所以应该又算完结了
