### ISSUE TITLE
您好我是从Unbreakabler过来的

### ISSUE THREAD

**Issue by shenyx110** [Minecraft-LightLand/L2Weaponry#4]
莱特兰部分武器无法正确被Unbreakabler打上标签
对方制作组说让我来问问你们
已知原版give指令可行
https://github.com/MCTeamPotato/Unbreakabler/issues/1

**Comment by lcy0x1** [comment]
因为我没调用Item的inventoryTick。我这里可以加兼容，但是遇到其他需要处理特殊机制的武器还是会出一样的问题。

下一版1.1.7可以修复。或者你加群，我给你一个临时的jar，QQ群或者Discord都行
