### ISSUE TITLE
Changing Ice and Fire Weapon Values

### ISSUE THREAD

**Issue by GlitchedGekko** [Minecraft-LightLand/L2Weaponry#8]
I was looking at the weapon dmg values for the ice and fire variants of your weapons and they seem very high. Most modpacks tweak the dmg values of ice and fire dragonsteel weapons to make them fit better and I wanted to know if that could be done here, as I see you have a config file built in for Twilight Forest but not Ice and Fire though the mod automatically adds the weapons.

**Comment by lcy0x1** [comment]
Use Attributizer to tweak weapon damage. It’s a great customization mod
